input:
  delete: no
  dir: "/tmp/input"
  #imap:
  #  server: ""
  #  username: ""
  #  password: ""
  #  mailbox: ""

output:
  # template for output file path or "stdout"
  file: "/tmp/html/{{ .ID }}.html"
  # file: "/tmp/html/{{ .ReportMetadata.Email }}/{{ .PolicyPublished.Domain }}!{{.ReportMetadata.DateRange.Begin}}!{{ .ReportMetadata.ReportID }}.html"
  # txt, json, html
  format: "html"
  assets_path: "./assets"

# perform reverse lookups?
lookup_addr: no
